# Generated by Django 6.1.1 on 2026-10-03 01:22

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('price_fcfa', models.PositiveIntegerField(verbose_name='Prix (FCFA)')),
                ('wave_link', models.URLField(blank=True, verbose_name='Lien de paiement Wave')),
                ('content_url', models.URLField(blank=True, verbose_name='Lien du contenu (vidéos, PDF, Drive…)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Groupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_info', models.CharField(blank=True, max_length=150, verbose_name='Prix / tarif')),
                ('deadline', models.DateField(verbose_name="Date limite d'inscription")),
                ('is_open', models.BooleanField(default=True, verbose_name='Ouvert')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='GroupageRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Numéro WhatsApp')),
                ('status', models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé : à payer'), ('paye', 'Payé'), ('commande', 'Commandé / en transit'), ('livre', 'Livré'), ('refuse', 'Refusé')], default='attente', max_length=10, verbose_name='Statut')),
                ('amount_fcfa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Montant (FCFA)')),
                ('payment_link', models.URLField(blank=True, verbose_name='Lien de paiement Wave')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(verbose_name='Produits / quantités souhaités')),
                ('groupage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.groupage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription groupage',
                'verbose_name_plural': 'Inscriptions groupage',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SheinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Numéro WhatsApp')),
                ('status', models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé : à payer'), ('paye', 'Payé'), ('commande', 'Commandé / en transit'), ('livre', 'Livré'), ('refuse', 'Refusé')], default='attente', max_length=10, verbose_name='Statut')),
                ('amount_fcfa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Montant (FCFA)')),
                ('payment_link', models.URLField(blank=True, verbose_name='Lien de paiement Wave')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart_link', models.URLField(blank=True, verbose_name='Lien du panier Shein')),
                ('screenshot', models.ImageField(blank=True, upload_to=core.models.upload_path, verbose_name='Capture du panier')),
                ('note', models.TextField(blank=True, verbose_name='Précisions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Shein',
                'verbose_name_plural': 'Demandes Shein',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé : à payer'), ('paye', 'Payé'), ('commande', 'Commandé / en transit'), ('livre', 'Livré'), ('refuse', 'Refusé')], default='attente', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formation')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('user', 'formation')},
            },
        ),
    ]
