# Generated by Django 6.1.1 on 2026-10-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='mode',
            field=models.CharField(choices=[('presentiel', 'En présentiel'), ('en_ligne', 'En ligne')], default='en_ligne', max_length=12, verbose_name='Mode de suivi'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro WhatsApp'),
        ),
        migrations.AddField(
            model_name='formation',
            name='audience',
            field=models.TextField(blank=True, verbose_name='Pour qui ? (une ligne par profil)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='cover',
            field=models.ImageField(blank=True, upload_to='formations/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='formation',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Durée (jours)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='faq',
            field=models.TextField(blank=True, verbose_name='Questions fréquentes (une ligne : Question | Réponse)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='instructor_bio',
            field=models.TextField(blank=True, verbose_name='Présentation de la formatrice'),
        ),
        migrations.AddField(
            model_name='formation',
            name='next_session',
            field=models.DateField(blank=True, null=True, verbose_name='Prochaine session'),
        ),
        migrations.AddField(
            model_name='formation',
            name='objectives',
            field=models.TextField(blank=True, verbose_name="Ce qu'on apprend (une ligne par objectif)"),
        ),
        migrations.AddField(
            model_name='formation',
            name='online_info',
            field=models.CharField(blank=True, max_length=200, verbose_name='Déroulement en ligne'),
        ),
        migrations.AddField(
            model_name='formation',
            name='onsite_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu du présentiel'),
        ),
        migrations.AddField(
            model_name='formation',
            name='program',
            field=models.TextField(blank=True, verbose_name='Programme (une ligne par jour : Titre | détail)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='rhythm',
            field=models.CharField(blank=True, max_length=150, verbose_name='Rythme / horaires'),
        ),
        migrations.AddField(
            model_name='formation',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, verbose_name='Promesse en une phrase'),
        ),
        migrations.AddField(
            model_name='formation',
            name='testimonials',
            field=models.TextField(blank=True, verbose_name='Témoignages (une ligne : Prénom | témoignage)'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(verbose_name='Présentation'),
        ),
    ]
