# Generated by Django 6.1.1 on 2026-10-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enrollment_mode_enrollment_whatsapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupage',
            name='price_info',
        ),
        migrations.AddField(
            model_name='groupage',
            name='air_delay',
            field=models.CharField(default='11 à 15 jours', max_length=80, verbose_name='Délai par avion'),
        ),
        migrations.AddField(
            model_name='groupage',
            name='sea_delay',
            field=models.CharField(default='environ 2 mois', max_length=80, verbose_name='Délai par bateau'),
        ),
        migrations.AddField(
            model_name='groupageregistration',
            name='mode',
            field=models.CharField(choices=[('avion', 'Avion'), ('bateau', 'Bateau')], default='avion', max_length=8, verbose_name='Transport'),
        ),
        migrations.AddField(
            model_name='groupageregistration',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='groupage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='groupageregistration',
            name='details',
            field=models.TextField(blank=True, verbose_name='Précisions (couleur, taille…)'),
        ),
        migrations.CreateModel(
            name='GroupageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Article')),
                ('image', models.ImageField(blank=True, upload_to='articles/', verbose_name='Photo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_fcfa', models.PositiveIntegerField(verbose_name="Prix de l'article (FCFA)")),
                ('transport_air_fcfa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Transport par avion (FCFA)')),
                ('transport_sea_fcfa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Transport par bateau (FCFA)')),
                ('groupage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.groupage')),
            ],
            options={
                'verbose_name': 'Article de groupage',
                'verbose_name_plural': 'Articles de groupage',
            },
        ),
        migrations.AddField(
            model_name='groupageregistration',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='core.groupagearticle'),
        ),
    ]
