# Generated by Django 6.1.1 on 2026-10-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_groupage_price_info_groupage_air_delay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='mode',
            field=models.CharField(choices=[('presentiel', 'En présentiel · 17h-19h'), ('en_ligne', 'En ligne · 21h-23h')], default='en_ligne', max_length=12, verbose_name='Mode de suivi'),
        ),
    ]
